name: dairy_farm
description: "Krishna Dairy Farm - Smart Farm Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  windows:
    generate: true
    image_path: "assets/images/krishna_logo.png"
    icon_size: 48
  image_path: "assets/images/krishna_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
